Adds conditional fetching, improves UX for devs
ConsenSys/Form-XChange pull request #18
Opened 2023-04-20 18:07 UTC by GuiBibeau

A few fixes:

- this will conditionally display forms only when the user is logged in. This is needed since we depend on MM connection to fetch some things client side
- It introduces error helpers
- it introduces a reusable way to get contract provider
-

NOTE:

- Give this a real QA round on a preview URL before merging.

2023-04-20 21:33 UTC, cxalem requested changes
We're getting an error fetching feedback form info on the home page, I left some comments with suggestions to fix this!

2023-04-20 21:33 UTC, cxalem commented on apps/web/components/FeedbackFormCard.tsx
> +      const contract = getFormContractClientInstance();
When you call `getFormContractClientInstance` you're fetching the Factory Contract, and here you should be fething the Feedback Form contract instead.

The method `getFormContractClientInstance` can receive a parameter that can be the address and use `FEEDBACK_FACTORY_CONTRACT_ADDRESS` as default.

2023-04-20 21:33 UTC, cxalem commented on apps/web/lib/contract.ts/contract.client.ts
> +export const getFormContractClientInstance = () => {
This function should receive the address as a parameter and have `FEEDBACK_FACTORY_CONTRACT_ADDRESS` as default.

2023-04-24 14:13 UTC, chin-flags approved these changes

2023-04-24 17:26 UTC, cxalem approved these changes

2023-04-24 17:27 UTC, merged